Add fail test

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -26,6 +26,11 @@ jobs:
         if: contains(github.event.head_commit.message, 'Create PR')
         run: |
             echo 'Running Create PR!'
+      - name: Fail GitHub Action
+        if: contains(github.event.head_commit.message, 'Fail')
+        run: |
+          echo 'Fail the build job'
+          exit 1
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v4
 
